project:
  type: website
  output-dir: docs
  output: docs

website:
  title: "Space Coast Chess Foundation"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: reference.qmd
        text: Builder's Reference
      - href: software-packages.qmd
        text: Software Packages

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]

editor: source