project:
  type: website
  output-dir: docs

website:
  title: "SpaceCoastChess"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: reference.qmd
        text: Builder's Reference

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source