project:
  type: website
  output-dir: docs
  output: docs

website:
  title: "Space Coast Chess Foundation"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: reference.qmd
        text: Builder's Reference
      - href: software-packages.qmd
        text: Software Packages
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css

editor: source